# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20180211_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.AlterField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
