# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
